<?php

use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Psr7\Response;
use PHPUnit\Framework\TestCase;
use Sentry\State\Hub;
use Sentry\State\HubInterface;
use SportMob\Translation\Client;
use SportMob\Translation\CacheAdapter;

class ClientTest extends TestCase
{
    private array $repsonseMock = [
        "Internazionale" => [
            "ar" => "إنترناسيونالي",
            "fa" => "اینتر میلان"
        ],
        "Real Madrid" => [
            "ar" => "ريال مدريد",
            "fa" => "رئال مادرید"
        ]
    ];
    private HubInterface $sentryHub;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->sentryHub = $this->getMockBuilder(HubInterface::class)->getMock();
    }

    public function testTranslateMustCallTranslationServiceApi()
    {
        (new CacheAdapter('redis'))->flushAll();

        $mock = new MockHandler([
            new Response(200, [], json_encode($this->repsonseMock)),
        ]);
        $handlerStack = HandlerStack::create($mock);
        $client = new Client('', 'redis', 6379, $this->sentryHub, $handlerStack);
        $response = $client->translate(array_keys($this->repsonseMock), ['ar', 'fa']);

        $this->assertEquals($this->repsonseMock, $response);

        $cacheAdapter = new CacheAdapter('redis');

        // check cache
        foreach ($this->repsonseMock as $keyword => $languages) {
            foreach ($languages as $language => $translation) {
                $this->assertEquals($cacheAdapter->get(Client::translateFormatKey($keyword, $language)), $translation);
            }
        }
    }

    public function testTranslateMustUseCacheInsteadOfTranslationServiceApi()
    {
        $responseMock = $this->repsonseMock;
        $responseMock['Internazionale']['fa'] = 'Meysam';
        $mock = new MockHandler([
            new Response(200, [], json_encode($responseMock)),
        ]);
        $handlerStack = HandlerStack::create($mock);
        $client = new Client('', 'redis', 6379, $this->sentryHub, $handlerStack);

        // this request must read data from cache
        $response = $client->translate(array_keys($this->repsonseMock), ['ar', 'fa']);

        $this->assertEquals($this->repsonseMock['Internazionale']['fa'], $response['Internazionale']['fa']);
    }

    public function testTranslateMustCallMissKeywordFromTranslationServiceApi()
    {

        // remove a key from cache
        $del = (new CacheAdapter('redis'))->del(Client::translateFormatKey('Internazionale', 'fa'));
        $this->assertTrue($del);

        $responseMock = $this->repsonseMock;
        $responseMock['Internazionale']['fa'] = 'Meysam';
        $mock = new MockHandler([
            new Response(200, [], json_encode($responseMock)),
        ]);
        $handlerStack = HandlerStack::create($mock);
        $client = new Client('', 'redis', 6379, $this->sentryHub, $handlerStack);

        // this request must read data from server
        $response = $client->translate(array_keys($this->repsonseMock), ['ar', 'fa']);

        $this->assertNotEquals($this->repsonseMock['Internazionale']['fa'], $response['Internazionale']['fa']);
    }

    public function testTranslationMustReturnEnglishIfServerIsDown()
    {
        (new CacheAdapter('redis'))->flushAll();
        $client = new Client('', 'redis', 6379,  $this->sentryHub);
        $response = $client->translate(array_keys($this->repsonseMock), ['ar', 'fa']);

        $this->assertIsArray($response);
        $this->assertArrayHasKey('Internazionale', $response);
        $this->assertArrayHasKey('Real Madrid', $response);
        foreach ($response as $keyword => $languageTranslate){
            foreach ($languageTranslate as $lang => $translate){
                $this->assertEquals($keyword, $translate); // all translation will be english, so all translation must be equal with english
            }
        }
    }

    public function testTranslationMustReturnEnglishIfLangIsEn()
    {
        $client = new Client('', 'redis', 6379,  $this->sentryHub);
        $respondMock = [
            'Internazionale' => ['en' => 'Internazionale'],
            'Real Madrid' => ['en' => 'Real Madrid'],
        ];
        $response = $client->translate(array_keys($respondMock), ['en']);

        $this->assertIsArray($response);
        $this->assertEquals($respondMock, $response);
    }

    public function testSearchMustCallTranslationServiceApi()
    {
        (new CacheAdapter('redis'))->flushAll();
        $strAr = 'ريال مدريد';
        $respondMock = ['Real Madrid CF', 'Real Madrid'];
        $mock = new MockHandler([
            new Response(200, [], json_encode($respondMock)),
        ]);
        $handlerStack = HandlerStack::create($mock);
        $client = new Client('', 'redis', 6379, $this->sentryHub, $handlerStack);
        $response = $client->search($strAr, 'ar');

        $this->assertEquals($respondMock, $response);

        // check cache
        $cacheAdapter = new CacheAdapter('redis');
        $cache = json_decode($cacheAdapter->get(Client::searchFormatKey($strAr, 'ar')), true); // convert string to array
        $this->assertEquals($cache, $respondMock);
    }

    public function testSearchMustCallReturnEmptyArrayIfServerIsDown()
    {
        (new CacheAdapter('redis'))->flushAll();
        $client = new Client('', 'redis', 6379,  $this->sentryHub);

        $strAr = 'ريال مدريد';
        $response = $client->search($strAr, 'ar');

        $this->assertCount(0, $response);
    }
}